[project]
name = "01"
version = "0.1.0"
description = "Week 1 Demo Code"
requires-python = ">=3.13"
dependencies = [
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "sentence-transformers>=5.2.0",
]
