project:
  type: website
  output-dir: dist
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!LICENSE.md"
format:
  html:
    theme: 
      light: flatly
      dark: darkly
execute:
  freeze: true
website:
  title: "CS-394"
  page-navigation: true
  sidebar:
    logo: theme/logos/DigiPen_Dragon_Shield_RGB_Black.png
    style: "docked"
    collapse-level: 2
    search: true
    contents:
      - text: "CS-394/594"
        href: index.qmd
      - text: "---"
      - section: "**Welcome**"
        contents:
          - text: "Slides"
            href: src/00/slides.qmd
            target: blank
          - text: "Syllabus"
            href: https://digipen824-my.sharepoint.com/:w:/g/personal/simon_guest_digipen_edu/IQDAYiVI08LMTaiWEhdq_j20AcJ8XmaTkdu4fQHdBJh86yQ?e=Cw9CTh
            target: blank
          - text: "Rubric (Weekly Assignments)"
            href: src/00/weekly-rubric.qmd
          - text: "Rubric (Final Project)"
            href: src/00/final-rubric.qmd
      - section: "**Week 1:** Foundations of Generative AI"
        contents:
          - text: "Slides"
            href: src/01/slides.qmd
            target: blank
          - text: "Resources"
            href: src/01/resources.qmd
          - section: "Notebooks"
            contents:
              - text: "hello-world.ipynb"
                href: src/01/notebooks/hello-world.ipynb
              - text: "word2vec.ipynb"
                href: src/01/notebooks/word2vec.ipynb
              - text: "translation-transformer.ipynb"
                href: src/01/notebooks/translation-transformer.ipynb
              - text: "GPT-2.ipynb"
                href: src/01/notebooks/GPT-2.ipynb
          - text: "Assignment"
            href: src/01/assignment.qmd
      - section: "**Week 2:** Exploring Hosted LLMs"
        contents:
          - text: "Slides"
            href: src/02/slides.qmd
            target: blank
          - text: "Resources"
            href: src/02/resources.qmd
          - section: "Notebooks"
            contents:
          - text: "Assignment"
            href: src/02/assignment.qmd
