project:
  type: website
  output-dir: dist
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!LICENSE.md"
format:
  html:
    theme: 
      light: flatly
      dark: darkly
execute:
  freeze: true
website:
  title: "CS-394"
  page-navigation: true
  sidebar:
    logo: theme/logos/DigiPen_Dragon_Shield_RGB_Black.png
    style: "docked"
    collapse-level: 2
    search: true
    contents:
      - text: "CS-394/594"
        href: index.qmd
      - text: "---"
      - section: "**Welcome**"
        contents:
          - text: "Slides"
            href: src/00/slides.qmd
            target: blank
          - text: "Syllabus"
            href: https://digipen824-my.sharepoint.com/:w:/g/personal/simon_guest_digipen_edu/IQDAYiVI08LMTaiWEhdq_j20AcJ8XmaTkdu4fQHdBJh86yQ?e=Cw9CTh
            target: blank
          - text: "Rubric (Weekly Assignments)"
            href: src/00/weekly-rubric.qmd
          - text: "Rubric (Final Project for CS-394)"
            href: src/00/final-rubric-394.qmd
          - text: "Rubric (Final Project for CS-594)"
            href: src/00/final-rubric-594.qmd
      - section: "**Module 1:** Foundations of Generative AI"
        contents:
          - text: "Slides"
            href: src/01/slides.qmd
            target: blank
          - text: "Resources"
            href: src/01/resources.qmd
          - section: "Notebooks"
            contents:
              - text: "hello-world.ipynb"
                href: src/01/notebooks/hello-world.ipynb
              - text: "word2vec.ipynb"
                href: src/01/notebooks/word2vec.ipynb
              - text: "translation-transformer.ipynb"
                href: src/01/notebooks/translation-transformer.ipynb
              - text: "GPT-2.ipynb"
                href: src/01/notebooks/GPT-2.ipynb
          - text: "Assignment"
            href: src/01/assignment.qmd
      - section: "**Module 2:** Exploring Hosted LLMs"
        contents:
          - text: "Slides"
            href: src/02/slides.qmd
            target: blank
          - text: "Resources"
            href: src/02/resources.qmd
          - section: "Notebooks"
            contents:
              - text: "instruction-tuned.ipynb"
                href: src/02/notebooks/instruction-tuned.ipynb
              - text: "chat-completion-openai.ipynb"
                href: src/02/notebooks/chat-completion-openai.ipynb
              - text: "chat-completion-openrouter.ipynb"
                href: src/02/notebooks/chat-completion-openrouter.ipynb
              - text: "token-streaming.ipynb"
                href: src/02/notebooks/token-streaming.ipynb
              - text: "structured-outputs.ipynb"
                href: src/02/notebooks/structured-outputs.ipynb
              - text: "gradio.ipynb"
                href: src/02/notebooks/gradio.ipynb
          - text: "Assignment"
            href: src/02/assignment.qmd
      - section: "**Module 3:** Agents and Tools"
        contents:
          - text: "Slides"
            href: src/03/slides.qmd
            target: blank
          - text: "Resources"
            href: src/03/resources.qmd
          - section: "Notebooks"
            contents:
              - text: "campus-agent.ipynb"
                href: src/03/notebooks/campus-agent.ipynb
              - text: "memory.ipynb"
                href: src/03/notebooks/memory.ipynb
              - text: "open-meteo-mcp.ipynb"
                href: src/03/notebooks/open-meteo-mcp.ipynb
          - text: "Assignment"
            href: src/03/assignment.qmd
      - section: "**Module 4:** Multimedia and Multimodal Models"
        contents:
          - text: "Slides"
            href: src/04/slides.qmd
            target: blank
          - text: "Resources"
            href: src/04/resources.qmd
          - section: "Notebooks"
            contents:
              - text: "text-to-image-sd-1.5.ipynb"
                href: src/04/notebooks/text-to-image-sd-1.5.ipynb
              - text: "image-to-image-sd-1.5.ipynb"
                href: src/04/notebooks/image-to-image-sd-1.5.ipynb
              - text: "text-to-image-replicate.ipynb"
                href: src/04/notebooks/text-to-image-replicate.ipynb
              - text: "generate-depth-map.ipynb"
                href: src/04/notebooks/generate-depth-map.ipynb
              - text: "depth-map-as-context.ipynb"
                href: src/04/notebooks/depth-map-as-context.ipynb
              - text: "inpainting.ipynb"
                href: src/04/notebooks/inpainting.ipynb
              - text: "outpainting.ipynb"
                href: src/04/notebooks/outpainting.ipynb
              - text: "controlnet-openpose-sd-1.5.ipynb"
                href: src/04/notebooks/controlnet-openpose-sd-1.5.ipynb
              - text: "pbr-creator.ipynb"
                href: src/04/notebooks/pbr-creator.ipynb
              - text: "vlm-gemma-3-4b.ipynb"
                href: src/04/notebooks/vlm-gemma-3-4b.ipynb
          - text: "Assignment"
            href: src/04/assignment.qmd
      - section: "**Module 5:** Running Models on Local Hardware"
        contents:
          - text: "Slides"
            href: src/05/slides.qmd
            target: blank
          - text: "Resources"
            href: src/05/resources.qmd
          - section: "Notebooks"
            contents:
              - text: "moe-heatmap.ipynb"
                href: src/05/notebooks/moe-heatmap.ipynb
              - text: "quantization.ipynb"
                href: src/05/notebooks/quantization.ipynb
              - text: "python-binding.ipynb"
                href: src/05/notebooks/python-binding.ipynb
          - text: "Assignment"
            href: src/05/assignment.qmd
      - section: "**Module 6:** Increasing Model Accuracy (Part 1)"
        contents:
          - text: "Slides"
            href: src/06/slides.qmd
            target: blank
          - text: "Resources"
            href: src/06/resources.qmd
          - section: "Notebooks"
            contents:
          - text: "Assignment"
            href: src/06/assignment.qmd
      - section: "**Module 7:** Increasing Model Accuracy (Part 2)"
        contents:
          - text: "Slides"
            href: src/07/slides.qmd
            target: blank
          - text: "Resources"
            href: src/07/resources.qmd
          - section: "Notebooks"
            contents:
          - text: "Assignment"
            href: src/07/assignment.qmd
      - section: "**Module 8:** Ethics, IP, and Safety"
        contents:
          - text: "Slides"
            href: src/08/slides.qmd
            target: blank
          - text: "Resources"
            href: src/08/resources.qmd
          - section: "Notebooks"
            contents:
          - text: "Assignment"
            href: src/08/assignment.qmd
