project:
  type: website
  output-dir: dist
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!LICENSE.md"
format:
  html:
    theme: 
      light: flatly
      dark: darkly
execute:
  freeze: true
website:
  title: "CS-394"
  page-navigation: true
  sidebar:
    logo: theme/logos/DigiPen_Dragon_Shield_RGB_Black.png
    style: "docked"
    collapse-level: 2
    search: true
    contents:
      - text: "CS-394/594"
        href: index.qmd
      - text: "---"
      - section: "**Welcome**"
        contents:
          - text: "Slides"
            href: src/00/slides.qmd
            target: blank
          - text: "Syllabus"
            href: https://digipen824-my.sharepoint.com/:w:/g/personal/simon_guest_digipen_edu/IQDAYiVI08LMTaiWEhdq_j20AcJ8XmaTkdu4fQHdBJh86yQ?e=Cw9CTh
            target: blank
          - text: "Rubric (Weekly Assignments)"
            href: src/00/weekly-rubric.qmd
          - text: "Rubric (Final Project)"
            href: src/00/final-rubric.qmd
      - section: "**Week 1:** Foundations of Generative AI"
        contents:
          - text: "Slides"
            href: src/01/slides.qmd
            target: blank
          - text: "Resources"
            href: src/01/resources.qmd
          - section: "Notebooks"
            contents:
              - text: "hello-world.ipynb"
                href: src/01/notebooks/hello-world.ipynb
              - text: "word2vec.ipynb"
                href: src/01/notebooks/word2vec.ipynb
              - text: "translation-transformer.ipynb"
                href: src/01/notebooks/translation-transformer.ipynb
              - text: "GPT-2.ipynb"
                href: src/01/notebooks/GPT-2.ipynb
          - text: "Assignment"
            href: src/01/assignment.qmd
      - section: "**Week 2:** Exploring Hosted LLMs"
        contents:
          - text: "Slides"
            href: src/02/slides.qmd
            target: blank
          - text: "Resources"
            href: src/02/resources.qmd
          - section: "Notebooks"
            contents:
              - text: "instruction-tuned.ipynb"
                href: src/02/notebooks/instruction-tuned.ipynb
              - text: "chat-completion-openai.ipynb"
                href: src/02/notebooks/chat-completion-openai.ipynb
              - text: "chat-completion-openrouter.ipynb"
                href: src/02/notebooks/chat-completion-openrouter.ipynb
              - text: "token-streaming.ipynb"
                href: src/02/notebooks/token-streaming.ipynb
          - text: "Assignment"
            href: src/02/assignment.qmd
      - section: "**Week 3:** Agents and Tools"
        contents:
          - text: "Slides"
            href: src/03/slides.qmd
            target: blank
          - text: "Resources"
            href: src/03/resources.qmd
          - section: "Notebooks"
            contents:
          - text: "Assignment"
            href: src/03/assignment.qmd
      - section: "**Week 4:** Multimedia and Multimodal Models"
        contents:
          - text: "Slides"
            href: src/04/slides.qmd
            target: blank
          - text: "Resources"
            href: src/04/resources.qmd
          - section: "Notebooks"
            contents:
          - text: "Assignment"
            href: src/04/assignment.qmd
      - section: "**Week 5:** Running Models on Local Hardware"
        contents:
          - text: "Slides"
            href: src/05/slides.qmd
            target: blank
          - text: "Resources"
            href: src/05/resources.qmd
          - section: "Notebooks"
            contents:
          - text: "Assignment"
            href: src/05/assignment.qmd
      - section: "**Week 6:** Increasing Model Accuracy (Part 1)"
        contents:
          - text: "Slides"
            href: src/06/slides.qmd
            target: blank
          - text: "Resources"
            href: src/06/resources.qmd
          - section: "Notebooks"
            contents:
          - text: "Assignment"
            href: src/06/assignment.qmd
      - section: "**Week 7:** Increasing Model Accuracy (Part 2)"
        contents:
          - text: "Slides"
            href: src/07/slides.qmd
            target: blank
          - text: "Resources"
            href: src/07/resources.qmd
          - section: "Notebooks"
            contents:
          - text: "Assignment"
            href: src/07/assignment.qmd
      - section: "**Week 8:** Ethics, IP, and Safety"
        contents:
          - text: "Slides"
            href: src/08/slides.qmd
            target: blank
          - text: "Resources"
            href: src/08/resources.qmd
          - section: "Notebooks"
            contents:
          - text: "Assignment"
            href: src/08/assignment.qmd
