project:
  type: website
  output-dir: dist
  render:
    - "*.qmd"
    - "*.ipynb"
    - "!LICENSE.md"
format:
  html:
    theme: 
      light: flatly
      dark: darkly
website:
  title: "CS-394"
  page-navigation: true
  sidebar:
    logo: theme/logos/DigiPen_Dragon_Shield_RGB_Black.png
    style: "docked"
    collapse-level: 2
    search: true
    contents:
      - text: "CS-394/594"
        href: index.qmd
      - text: "---"
      - section: "Welcome!"
        contents:
          - text: "Slides"
            href: src/00/slides.qmd
            target: blank
      - section: "Week 1: Foundations of Generative AI"
        contents:
          - text: "Slides"
            href: src/01/slides.qmd
            target: blank
          - text: "Resources"
            href: src/01/resources.qmd
          - section: "Hands-on Notebooks"
            contents:
              - text: "hello-world.ipynb"
                href: src/01/hello-world.ipynb
              - text: "word2vec.ipynb"
                href: src/01/word2vec.ipynb
              - text: "sentence-transformer.ipynb"
                href: src/01/sentence-transformer.ipynb
              - text: "GPT-2.ipynb"
                href: src/01/GPT-2.ipynb
          - text: "Assignment"
            href: src/01/assignment.qmd
