[project]
name = "cs-394"
version = "0.1.0"
description = "Code and content for DigiPen CS-394"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "quarto-cli>=1.7.31",
]

[tool.uv.workspace]
members = ["src/01"]
