[project]
name = "02"
version = "0.1.0"
description = "Week 2 Demo Code"
requires-python = ">=3.13"
dependencies = [
    "gradio>=6.2.0",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "openai>=2.14.0",
    "pydantic>=2.12.5",
    "python-dotenv>=1.2.1",
]
