[project]
name = "02"
version = "0.1.0"
description = "Week 2 Demo Code"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "ipywidgets>=8.1.8",
    "jupyter>=1.1.1",
    "matplotlib>=3.10.8",
    "openai>=2.14.0",
]
