[project]
name = "07"
version = "0.1.0"
description = "Module 7 Demo Code"
requires-python = ">=3.13"
dependencies = [
    "datasets>=4.5.0",
    "peft>=0.18.1",
    "torch>=2.9.1",
    "transformers>=4.57.3",
    "trl>=0.28.0",
]
